# Generated by Django 4.0.4 on 2022-05-27 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('cnfpassword', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('dob', models.DateField()),
                ('num', models.CharField(max_length=15)),
                ('gender', models.CharField(max_length=15)),
            ],
        ),
    ]
